
server:
  port: 8080
# para rodar a aplicação do intellij

spring:
  application:
    name: cadastro


  datasource:
    username: 'financeira'
    password: '123456'
    url: jdbc:postgresql://localhost:15432/clientes

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'


    hibernate:
      ddl-auto: 'create-drop'
---

# rodar a aplicação do container
#spring:
#  application:
#    name: cliente
#
#  datasource:
#    username: 'financeira'
#    password: '123456'
#    url: jdbc:postgresql://postgres-compose:5432/clientes
#
#  jpa:
#    show-sql: 'true'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: 'true'
#
#
#    hibernate:
#      ddl-auto: 'create-drop'

#banco de teste da aplicação em h2

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    username: 'sa'
#    password: 'sa'

#  jpa:
#    hibernate:
#      dll-auto: 'create-drop'
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true