
server:
  port: 8080
# para rodar a aplicação do intellij
spring:
  application:
    name: cliente

  datasource:
    username: 'financeira'
    password: '123456'
    url: jdbc:postgresql://localhost:15432/clientes

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'


    hibernate:
      ddl-auto: 'create-drop'

# rodar a aplicação do container
#spring:
#  application:
#    name: cliente
#
#  datasource:
#    username: 'financeira'
#    password: '123456'
#    url: jdbc:postgresql://postgres-compose:5432/clientes
#
#  jpa:
#    show-sql: 'true'
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: 'true'
#
#
#    hibernate:
#      ddl-auto: 'create-drop'